export const dishes = () => [
    {
        id: 1,
        name: 'Super Duo',
        description: '(1) Sub b.m.t 15 cm + (1) sub pizza 15cm.',
        price: 6500,
        imgSrc: 'd1_super_duo.png',
        restaurantId: 1,
        restaurantName: 'Subway',
        discount: '22%',
    },
    {
        id: 2,
        name: 'Sub Del Día Lunes',
        description: '(1) Sub Salame tomate 15cm',
        price: 3850,
        imgSrc: 'd1_sub_del_dia_lunes.png',
        restaurantId: 1,
        restaurantName: 'Subway',
        discount: '15%',
    },
    {
        id: 3,
        name: 'Footlover',
        description: '(1) Sub atún footlong 30 cm + (1) bebida de lata.',
        price: 8450,
        imgSrc: 'd1_footlover.png',
        restaurantId: 1,
        restaurantName: 'Subway',
        discount: '27%',
    },
    {
        id: 4,
        name: 'Date Un Gusto',
        description: '(1) Sub pollo asado 15cm + (1) galleta.',
        price: 5900,
        imgSrc: 'd1_date_un_gusto.png',
        restaurantId: 1,
        restaurantName: 'Subway',
        discount: '30%',
    },
    {
        id: 5,
        name: 'Dupla Maestra',
        description: '2 Churrascos Italianos, Papas Fritas Grandes, 5 empanadas de queso y 2 Bebidas Lata',
        price: 5900,
        imgSrc: 'd2_dupla_maestra.png',
        restaurantId: 2,
        restaurantName: 'Juan Maestro',
        discount: '30%',
    },
    {
        id: 6,
        name: 'Selección Maestra',
        description: 'Lomo Chacarero + Pollo Italiano + Churrasco Granjero + Palta Mayo + Barros Luco',
        price: 7850,
        imgSrc: 'd2_seleccion_maestra.png',
        restaurantId: 2,
        restaurantName: 'Juan Maestro',
        discount: '15%',
    },
    {
        id: 7,
        name: 'triple B Maestro',
        description: '3 Sándwiches Churrasco o Lomo Palta Mayo + 3 Papas Fritas Pequeñas + 3 Bebidas de lata',
        price: 8450,
        imgSrc: 'd2_triple_b_maestro.png',
        restaurantId: 2,
        restaurantName: 'Juan Maestro',
        discount: '27%',
    },
    {
        id: 8,
        name: 'Combo Churrasco',
        description: 'Sándwich Churrasco, (Italiano o Chacarero o luco) + Papas Fritas Normal + Bebida en lata.',
        price: 5900,
        imgSrc: 'd2_combo_churrasco.png',
        restaurantId: 2,
        restaurantName: 'Juan Maestro',
        discount: '30%',
    },
    {
        id: 9,
        name: 'Chicken Lo Mein',
        description: 'Fideos chinos a base de huevo salteados con pollo y nuestra salsa dark',
        price: 5900,
        imgSrc: 'd3_Chicken_Lo_Mein.png',
        restaurantId: 4,
        restaurantName: 'China Gaoming',
        discount: '30%',
    },
    {
        id: 10,
        name: 'Mongolian Beef',
        description: 'Trozos de carne de res salteados en salsa mongolian y cebollín',
        price: 3850,
        imgSrc: 'd3_mongolian_Beef.png',
        restaurantId: 4,
        restaurantName: 'China Gaoming',
        discount: '15%',
    },
    {
        id: 11,
        name: 'Pad Thai',
        description: 'Fideos de arroz salteados con pollo en Salsa Thai ligeramente picante',
        price: 8450,
        imgSrc: 'd3_pad_thai.png',
        restaurantId: 4,
        restaurantName: 'China Gaoming',
        discount: '27%',
    },
    // Agrega más platos aquí según sea necesario...incorpar tambien la imagen en src/front/img, debe tener el mismo nombre en imgSrc
];
