// src/front/js/component/restaurants.js
export const restaurants = () => [
    {
        id: 1,
        name: 'Subway',
        country: 'USA',
        category: 'Sandwiches',
        rating: 3.8,
        deliveryTime: 15,
        price: 470,
        imgSrc: 'r1_subway.png',
        discount: '30% Off',
        special: true
    },
    {
        id: 2,
        name: 'Juan Maestro',
        country: 'USA',
        category: 'Sandwiches',
        rating: 3.5,
        deliveryTime: 24,
        price: 490,
        imgSrc: 'r1_juan_maestro.png',
        discount: '34% Off',
        special: true
    },
    {
        id: 3,
        name: 'Bajón de la Noche',
        country: 'USA',
        category: 'Sandwiches',
        rating: 4.1,
        deliveryTime: 39,
        price: 1490,
        imgSrc: 'r1_bajon de la Noche.png',
        discount: '30% Off',
        special: true
    },
    {
        id: 4,
        name: 'China Gaoming',
        country: 'China',
        category: 'Chinese',
        rating: 4.6,
        deliveryTime: 15,
        price: 1290,
        imgSrc: 'r2_comida_china_gaoming.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 5,
        name: 'Danubio Azul',
        country: 'China',
        category: 'Chinese',
        rating: 4.7,
        deliveryTime: 29,
        price: 1390,
        imgSrc: 'r2_palacio_danubio_azul.png',
        discount: 'Lleva 2, paga 1',
        special: true
    },
    {
        id: 6,
        name: 'Fu Lin',
        country: 'China',
        category: 'Chinese',
        rating: 4.3,
        deliveryTime: 15,
        price: 590,
        imgSrc: 'r2_fu_lin.png',
        discount: '20% Off',
        special: true
    },
    {
        id: 7,
        name: 'Corea Express',
        country: 'Korea',
        category: 'Corea',
        rating: 4.3,
        deliveryTime: 24,
        price: 270,
        imgSrc: 'r3_corea_express.png',
        discount: '55% Off',
        special: true
    },

    {
        id: 8,
        name: 'Seul',
        country: 'Korea',
        category: 'Corea',
        rating: 4.5,
        deliveryTime: 29,
        price: 1190,
        imgSrc: 'r3_seul.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 9,
        name: 'arabito deluxe',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.7,
        deliveryTime: 29,
        price: 1190,
        imgSrc: 'r4_arabito_deluxe.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 10,
        name: 'Emporio Madrid',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.7,
        deliveryTime: 34,
        price: 1190,
        imgSrc: 'r4_emporio_madrid.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 11,
        name: 'Casa Lai',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.3,
        deliveryTime: 29,
        price: 1290,
        imgSrc: 'r4_casa_lai.png',
        discount: 'Envío Gratis',
        special: true
    },


    {
        id: 12,
        name: 'Swagat India',
        country: 'India',
        category: 'Indian',
        rating: 4.7,
        deliveryTime: 15,
        price: 590,
        imgSrc: 'r5_swagat_comida_india.png',
        discount: '20% Off',
        special: true
    },
    {
        id: 13,
        name: 'Lasañas Santiago',
        country: 'Italia',
        category: 'Pasta',
        rating: 3.8,
        deliveryTime: 34,
        price: 1190,
        imgSrc: 'r6_lasanas_santiago.png',
        discount: '20% Off',
        special: true
    },
    {
        id: 14,
        name: 'Montalbano',
        country: 'Italia',
        category: 'Pasta',
        rating: 3.5,
        deliveryTime: 29,
        price: 590,
        imgSrc: 'r6_montalbano.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 15,
        name: 'Espresso Pizza',
        country: 'Italia',
        category: 'Pizza',
        rating: 4.7,
        deliveryTime: 29,
        price: 1890,
        imgSrc: 'r6_espresso_pizza.png',
        discount: '35% Off',
        special: true
    },
    {
        id: 16,
        name: 'Sushi Blues',
        country: 'Japan',
        category: 'Sushi',
        rating: 3.8,
        deliveryTime: 29,
        price: 890,
        imgSrc: 'r7_sushi_blues.png',
        discount: 'Lleva 2, paga 1',
        special: true
    },
    {
        id: 17,
        name: 'Kento',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.3,
        deliveryTime: 29,
        price: 1290,
        imgSrc: 'r7_kento.png',
        discount: 'Lleva 2, paga 1',
        special: true
    },
    {
        id: 18,
        name: 'Itacate',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.0,
        deliveryTime: 34,
        price: 1290,
        imgSrc: 'r8_itacate.png',
        discount: '35% Off',
        special: true
    },
    {
        id: 19,
        name: 'Tommy Beans',
        country: 'Mexico',
        category: 'Tacos',
        rating: 3.9,
        deliveryTime: 29,
        price: 790,
        imgSrc: 'r8_tommy_beans.png',
        discount: '31% Off',
        special: true
    },

    /*    {
        id: 4,
        name: 'El Rincón de Abril',
        country: 'USA',
        category: 'Sandwiches',
        rating: 3.2,
        deliveryTime: 34,
        price: 1490,
        imgSrc: 'el_rincon_de_abril.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 5,
        name: 'San Camilo Salón de Té',
        country: 'USA',
        category: 'Sandwiches',
        rating: 4.9,
        deliveryTime: 29,
        price: 1390,
        imgSrc: 'san_camilo.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 6,
        name: 'Chicktruck',
        country: 'USA',
        category: 'Sandwiches',
        rating: 4.9,
        deliveryTime: 34,
        price: 1490,
        imgSrc: 'chicktruck.png',
        discount: 'Envío Gratis',
        special: true
    },
    
    {
        id: 10,
        name: 'Il Vicino',
        country: 'Italia',
        category: 'Pizza',
        rating: 4.4,
        deliveryTime: 39,
        price: 1890,
        imgSrc: 'il_vicino.png',
        discount: '35% Off',
        special: true
    },
    {
        id: 11,
        name: 'Pizza Nostra',
        country: 'Italia',
        category: 'Pizza',
        rating: 4.5,
        deliveryTime: 19,
        price: 990,
        imgSrc: 'pizza_nostra.png',
        discount: '29% Off',
        special: true
    },
    {
        id: 12,
        name: 'Pizzeria Tarantella',
        country: 'Italia',
        category: 'Pizza',
        rating: 4.1,
        deliveryTime: 39,
        price: 1690,
        imgSrc: 'pizzeria_tarantella.png',
        discount: '1500 Off en Envío',
        special: true
    },
    {
        id: 13,
        name: 'La Ruffina',
        country: 'Italia',
        category: 'Pasta',
        rating: 4.4,
        deliveryTime: 34,
        price: 890,
        imgSrc: 'la_ruffina.png',
        discount: '36% Off',
        special: true
    },
    {
        id: 14,
        name: 'Irreverente',
        country: 'Italia',
        category: 'Pasta',
        rating: 4.8,
        deliveryTime: 34,
        price: 370,
        imgSrc: 'irreverente.png',
        discount: '40% Off',
        special: true
    },
    {
        id: 15,
        name: 'El Foodtruck de Las Delicias',
        country: 'Italia',
        category: 'Pasta',
        rating: 4.4,
        deliveryTime: 24,
        price: 790,
        imgSrc: 'el_foodtruck_de_las_delicias.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 16,
        name: 'Vapiano',
        country: 'Italia',
        category: 'Pasta',
        rating: 4.4,
        deliveryTime: 39,
        price: 990,
        imgSrc: 'vapiano.png',
        discount: 'Envío Gratis',
        special: true
    },
    
    {
        id: 19,
        name: 'Guacamole Tex Mex',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.9,
        deliveryTime: 15,
        price: 470,
        imgSrc: 'guacamole_tex_mex.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 20,
        name: 'Taco Bell',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.4,
        deliveryTime: 15,
        price: 590,
        imgSrc: 'taco_bell.png',
        discount: '48% Off',
        special: true
    },
    {
        id: 21,
        name: 'Autentiko French Tacos',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.9,
        deliveryTime: 19,
        price: 1190,
        imgSrc: 'autentiko_french_tacos.png',
        discount: '30% Off',
        special: true
    },
    {
        id: 22,
        name: 'El Mariachi Tacos Grill',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.8,
        deliveryTime: 24,
        price: 1490,
        imgSrc: 'el_mariachi_tacos_grill.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 23,
        name: 'Guacamole Tex Mex',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.4,
        deliveryTime: 29,
        price: 1290,
        imgSrc: 'guacamole_tex_mex.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 24,
        name: 'La Enchilada',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.7,
        deliveryTime: 29,
        price: 990,
        imgSrc: 'la_enchilada.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 25,
        name: 'Mexicanos',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.7,
        deliveryTime: 29,
        price: 990,
        imgSrc: 'mexicanos.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 26,
        name: 'Taqueria Th',
        country: 'Mexico',
        category: 'Tacos',
        rating: 4.1,
        deliveryTime: 19,
        price: 890,
        imgSrc: 'taqueria_th.png',
        discount: '30% Off',
        special: true
    },
    
    {
        id: 29,
        name: 'Nikkei Sushi Providencia',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.1,
        deliveryTime: 29,
        price: 1290,
        imgSrc: 'nikkei_sushi_providencia.png',
        discount: '55% Off',
        special: true
    },
    {
        id: 30,
        name: 'Yu Sushi',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.1,
        deliveryTime: 54,
        price: 1290,
        imgSrc: 'yu_sushi.png',
        discount: '45% Off',
        special: true
    },
    {
        id: 31,
        name: 'Oceanika Sushi',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.3,
        deliveryTime: 19,
        price: 490,
        imgSrc: 'oceanika_sushi.png',
        discount: '40% Off',
        special: true
    },
    {
        id: 32,
        name: 'Sayonara Sushi Vip',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.2,
        deliveryTime: 34,
        price: 1190,
        imgSrc: 'sayonara_sushi_vip.png',
        discount: '45% Off',
        special: true
    },
    {
        id: 33,
        name: 'Sushithais Encanto',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.6,
        deliveryTime: 34,
        price: 1690,
        imgSrc: 'sushithais_encanto.png',
        discount: '20% Off',
        special: true
    },
    {
        id: 34,
        name: 'All Rice Food',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.6,
        deliveryTime: 24,
        price: 790,
        imgSrc: 'all_rice_food.png',
        discount: '30% Off',
        special: true
    },
    {
        id: 35,
        name: 'Fukai',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.7,
        deliveryTime: 24,
        price: 490,
        imgSrc: 'fukai.png',
        discount: '40% Off',
        special: true
    },
    {
        id: 36,
        name: 'Nikkei 57',
        country: 'Japan',
        category: 'Sushi',
        rating: 4.4,
        deliveryTime: 49,
        price: 1890,
        imgSrc: 'nikkei_57.png',
        discount: '36% Off',
        special: true
    },
    {
        id: 37,
        name: 'Ramen One',
        country: 'Japan',
        category: 'Ramen',
        rating: 4.7,
        deliveryTime: 19,
        price: 990,
        imgSrc: 'ramen_one.png',
        discount: '35% Off',
        special: true
    },



    {
        id: 44,
        name: 'Ruta Tercera Comida China',
        country: 'China',
        category: 'Chinese',
        rating: 4.1,
        deliveryTime: 19,
        price: 470,
        imgSrc: 'ruta_tercera_comida_china.png',
        discount: '60% Off',
        special: true
    },
    {
        id: 45,
        name: 'Noodlewok',
        country: 'China',
        category: 'Chinese',
        rating: 4.1,
        deliveryTime: 39,
        price: 1690,
        imgSrc: 'noodlewok.png',
        discount: '1500 Off en Envío',
        special: true
    },
    {
        id: 46,
        name: 'Xin Hua',
        country: 'China',
        category: 'Chinese',
        rating: 4.7,
        deliveryTime: 15,
        price: 690,
        imgSrc: 'xin_hua.png',
        discount: 'Envío Gratis',
        special: true
    },
    
    {
        id: 50,
        name: 'Rest Wok Grill Quinta Normal',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.7,
        deliveryTime: 44,
        price: 1390,
        imgSrc: 'rest_wok_grill_quinta_normal.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 51,
        name: 'Maycha Cocina Peruana',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.9,
        deliveryTime: 34,
        price: 1690,
        imgSrc: 'maycha_cocina_peruana.png',
        discount: '1500 Off en Envío',
        special: true
    },
    {
        id: 52,
        name: 'Mr Qiu',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.9,
        deliveryTime: 24,
        price: 1290,
        imgSrc: 'mr_qiu.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 53,
        name: 'Inti Gastronomia Peruana',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.9,
        deliveryTime: 34,
        price: 1490,
        imgSrc: 'inti_gastronomia_peruana.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 54,
        name: 'Restaurant Camino Del Inca',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.9,
        deliveryTime: 29,
        price: 1090,
        imgSrc: 'restaurant_camino_del_inca.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 55,
        name: 'Mostachos Bistro',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.9,
        deliveryTime: 34,
        price: 1290,
        imgSrc: 'mostachos_bistro.png',
        discount: 'Envío Gratis',
        special: true
    },
    {
        id: 56,
        name: 'Arabian Fusion Food Barrio Italia',
        country: 'Spain',
        category: 'Spanish',
        rating: 4.9,
        deliveryTime: 19,
        price: 1190,
        imgSrc: 'arabian_fusion_food_barrio_italia.png',
        discount: 'Envío Gratis',
        special: true
    }*/
];
