"""empty message

Revision ID: 21a5534201be
Revises: 3127d2678f1d
Create Date: 2024-08-01 15:18:35.144103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a5534201be'
down_revision = '3127d2678f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.drop_constraint('paymentMethods_card_cvv_key', type_='unique')
        batch_op.drop_column('card_cvv')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('ratings_starts_key', type_='unique')
        batch_op.create_unique_constraint(None, ['stars'])
        batch_op.drop_column('starts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('ratings_starts_key', ['starts'])
        batch_op.drop_column('stars')

    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_cvv', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('paymentMethods_card_cvv_key', ['card_cvv'])

    # ### end Alembic commands ###
