"""empty message

Revision ID: 39697a208ec4
Revises: 7ea0686c8b24
Create Date: 2024-08-06 14:39:26.840913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39697a208ec4'
down_revision = '7ea0686c8b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_date', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('cvv2', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['exp_date'])
        batch_op.create_unique_constraint(None, ['cvv2'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cvv2')
        batch_op.drop_column('exp_date')

    # ### end Alembic commands ###
