"""empty message

Revision ID: 5e601eb5624c
Revises: 21a5534201be
Create Date: 2024-08-01 15:21:08.000692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e601eb5624c'
down_revision = '21a5534201be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.drop_constraint('paymentMethods_card_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.create_unique_constraint('paymentMethods_card_number_key', ['card_number'])

    # ### end Alembic commands ###
