"""empty message

Revision ID: 7a44f5e222fb
Revises: be01d04ac007
Create Date: 2024-07-31 19:53:19.698386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a44f5e222fb'
down_revision = 'be01d04ac007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('img', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['img'])
        batch_op.drop_constraint('dishes_restaurants_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('dishes_categories_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'])
        batch_op.drop_column('categories_id')
        batch_op.drop_column('restaurants_id')

    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('paymentMethods_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('users_id')

    with op.batch_alter_table('pedidoDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dish_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('pedidoDetails_category_name_key', type_='unique')
        batch_op.drop_constraint('pedidoDetails_category_product_key', type_='unique')
        batch_op.create_unique_constraint(None, ['price'])
        batch_op.create_unique_constraint(None, ['quantity'])
        batch_op.drop_constraint('pedidoDetails_orden_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dishes', ['dish_id'], ['id'])
        batch_op.create_foreign_key(None, 'pedidos', ['pedido_id'], ['id'])
        batch_op.drop_column('category_name')
        batch_op.drop_column('category_product')
        batch_op.drop_column('orden_id')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('pedidos_category_name_key', type_='unique')
        batch_op.drop_constraint('pedidos_category_product_key', type_='unique')
        batch_op.create_unique_constraint(None, ['date'])
        batch_op.drop_constraint('pedidos_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('users_id')
        batch_op.drop_column('category_name')
        batch_op.drop_column('category_product')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('profiles_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('users_id')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('ratings_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ratings_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profiles_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_product', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pedidos_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('pedidos_category_product_key', ['category_product'])
        batch_op.create_unique_constraint('pedidos_category_name_key', ['category_name'])
        batch_op.drop_column('date')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('pedidoDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category_product', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pedidoDetails_orden_id_fkey', 'pedidos', ['orden_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('pedidoDetails_category_product_key', ['category_product'])
        batch_op.create_unique_constraint('pedidoDetails_category_name_key', ['category_name'])
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('dish_id')
        batch_op.drop_column('pedido_id')

    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('paymentMethods_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurants_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dishes_categories_id_fkey', 'categories', ['categories_id'], ['id'])
        batch_op.create_foreign_key('dishes_restaurants_id_fkey', 'restaurants', ['restaurants_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('img')
        batch_op.drop_column('restaurant_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
