"""empty message

Revision ID: 7ea0686c8b24
Revises: 5e601eb5624c
Create Date: 2024-08-01 15:22:39.698176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea0686c8b24'
down_revision = '5e601eb5624c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.drop_constraint('paymentMethods_card_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['card_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentMethods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('paymentMethods_card_name_key', ['card_name'])

    # ### end Alembic commands ###
