"""empty message

Revision ID: be01d04ac007
Revises: 285b61c0aa39
Create Date: 2024-07-31 19:12:01.108885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be01d04ac007'
down_revision = '285b61c0aa39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('img', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('img')
    )
    op.create_table('paymentMethods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=120), nullable=False),
    sa.Column('card_number', sa.String(length=120), nullable=False),
    sa.Column('card_cvv', sa.String(length=120), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_cvv'),
    sa.UniqueConstraint('card_name'),
    sa.UniqueConstraint('card_number')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_product', sa.String(length=120), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('category_product')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=120), nullable=False),
    sa.Column('starts', sa.String(length=120), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comments'),
    sa.UniqueConstraint('starts')
    )
    op.create_table('pedidoDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_product', sa.String(length=120), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('category_product')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.String(length=120), nullable=False),
    sa.Column('deliveryTime', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.Column('img', sa.String(length=120), nullable=False),
    sa.Column('discount', sa.String(length=120), nullable=False),
    sa.Column('special', sa.String(length=120), nullable=False),
    sa.Column('categories_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('deliveryTime'),
    sa.UniqueConstraint('discount'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('rating'),
    sa.UniqueConstraint('special')
    )
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.Column('restaurantId', sa.String(length=120), nullable=False),
    sa.Column('restaurantName', sa.String(length=120), nullable=False),
    sa.Column('discount', sa.String(length=120), nullable=False),
    sa.Column('restaurants_id', sa.Integer(), nullable=False),
    sa.Column('categories_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['restaurants_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('discount'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('restaurantId'),
    sa.UniqueConstraint('restaurantName')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['address'])
        batch_op.create_unique_constraint(None, ['avatar'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('address')
        batch_op.drop_column('avatar')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    op.drop_table('dishes')
    op.drop_table('restaurants')
    op.drop_table('pedidoDetails')
    op.drop_table('ratings')
    op.drop_table('pedidos')
    op.drop_table('paymentMethods')
    op.drop_table('categories')
    # ### end Alembic commands ###
